using AutoPecasERP.Core.Entities; using Microsoft.EntityFrameworkCore;
namespace AutoPecasERP.Data.Context;
public class ErpDbContext:DbContext {
 public DbSet<Usuario> Usuarios=>Set<Usuario>(); public DbSet<Cliente> Clientes=>Set<Cliente>(); public DbSet<Produto> Produtos=>Set<Produto>(); public DbSet<Fornecedor> Fornecedores=>Set<Fornecedor>(); public DbSet<MovimentacaoEstoque> MovimentacoesEstoque=>Set<MovimentacaoEstoque>(); public DbSet<PedidoCompra> PedidosCompra=>Set<PedidoCompra>(); public DbSet<ItemPedidoCompra> ItensPedidoCompra=>Set<ItemPedidoCompra>(); public DbSet<ContaPagar> ContasPagar=>Set<ContaPagar>(); public DbSet<Auditoria> Auditorias=>Set<Auditoria>(); public DbSet<Venda> Vendas=>Set<Venda>(); public DbSet<ItemVenda> ItensVenda=>Set<ItemVenda>(); public DbSet<ContaReceber> ContasReceber=>Set<ContaReceber>(); public DbSet<ConfiguracaoFiscal> ConfiguracoesFiscais=>Set<ConfiguracaoFiscal>(); public DbSet<NotaFiscal> NotasFiscais=>Set<NotaFiscal>(); public DbSet<EventoFiscal> EventosFiscais=>Set<EventoFiscal>(); public DbSet<Caixa> Caixas=>Set<Caixa>(); public DbSet<MovimentoCaixa> MovimentosCaixa=>Set<MovimentoCaixa>(); public DbSet<BaixaFinanceira> BaixasFinanceiras=>Set<BaixaFinanceira>(); public DbSet<VeiculoCliente> VeiculosCliente=>Set<VeiculoCliente>(); public DbSet<OrdemServico> OrdensServico=>Set<OrdemServico>(); public DbSet<ItemOrdemServico> ItensOrdemServico=>Set<ItemOrdemServico>(); public DbSet<OportunidadeCrm> OportunidadesCrm=>Set<OportunidadeCrm>(); public DbSet<InteracaoCrm> InteracoesCrm=>Set<InteracaoCrm>(); public DbSet<VendaPerdida> VendasPerdidas=>Set<VendaPerdida>(); public DbSet<PermissaoPerfil> PermissoesPerfil=>Set<PermissaoPerfil>(); public DbSet<VersaoBanco> VersoesBanco=>Set<VersaoBanco>(); public DbSet<HistoricoCusto> HistoricosCusto=>Set<HistoricoCusto>();
 public DbSet<CotacaoCompra> CotacoesCompra=>Set<CotacaoCompra>(); public DbSet<ItemCotacaoCompra> ItensCotacaoCompra=>Set<ItemCotacaoCompra>(); public DbSet<OfertaFornecedor> OfertasFornecedor=>Set<OfertaFornecedor>(); public DbSet<TabelaPreco> TabelasPreco=>Set<TabelaPreco>(); public DbSet<ParcelaFinanceira> ParcelasFinanceiras=>Set<ParcelaFinanceira>(); public DbSet<ComissaoVenda> ComissoesVenda=>Set<ComissaoVenda>();
 protected override void OnConfiguring(DbContextOptionsBuilder b){ var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AutoPecasConcorrenteERP"); Directory.CreateDirectory(dir); b.UseSqlite($"Data Source={Path.Combine(dir,"erp.db")}"); }
 protected override void OnModelCreating(ModelBuilder m){m.Entity<Usuario>().HasIndex(x=>x.Login).IsUnique();m.Entity<Produto>().HasIndex(x=>x.CodigoInterno).IsUnique();m.Entity<PedidoCompra>().HasIndex(x=>x.Numero).IsUnique();m.Entity<PedidoCompra>().HasOne(x=>x.Fornecedor).WithMany().HasForeignKey(x=>x.FornecedorId).OnDelete(DeleteBehavior.Restrict);m.Entity<ItemPedidoCompra>().HasOne(x=>x.PedidoCompra).WithMany(x=>x.Itens).HasForeignKey(x=>x.PedidoCompraId);m.Entity<ItemPedidoCompra>().HasOne(x=>x.Produto).WithMany().HasForeignKey(x=>x.ProdutoId).OnDelete(DeleteBehavior.Restrict);m.Entity<MovimentacaoEstoque>().HasOne(x=>x.Produto).WithMany().HasForeignKey(x=>x.ProdutoId).OnDelete(DeleteBehavior.Restrict);m.Entity<Venda>().HasIndex(x=>x.Numero).IsUnique();m.Entity<Venda>().HasOne(x=>x.Cliente).WithMany().HasForeignKey(x=>x.ClienteId).OnDelete(DeleteBehavior.Restrict);m.Entity<ItemVenda>().HasOne(x=>x.Venda).WithMany(x=>x.Itens).HasForeignKey(x=>x.VendaId);m.Entity<ItemVenda>().HasOne(x=>x.Produto).WithMany().HasForeignKey(x=>x.ProdutoId).OnDelete(DeleteBehavior.Restrict);m.Entity<NotaFiscal>().HasOne(x=>x.Venda).WithMany().HasForeignKey(x=>x.VendaId).OnDelete(DeleteBehavior.Restrict);m.Entity<EventoFiscal>().HasOne(x=>x.NotaFiscal).WithMany(x=>x.Eventos).HasForeignKey(x=>x.NotaFiscalId);m.Entity<MovimentoCaixa>().HasOne(x=>x.Caixa).WithMany(x=>x.Movimentos).HasForeignKey(x=>x.CaixaId);m.Entity<VeiculoCliente>().HasOne(x=>x.Cliente).WithMany().HasForeignKey(x=>x.ClienteId).OnDelete(DeleteBehavior.Restrict);m.Entity<OrdemServico>().HasIndex(x=>x.Numero).IsUnique();m.Entity<OrdemServico>().HasOne(x=>x.Cliente).WithMany().HasForeignKey(x=>x.ClienteId).OnDelete(DeleteBehavior.Restrict);m.Entity<OrdemServico>().HasOne(x=>x.Veiculo).WithMany().HasForeignKey(x=>x.VeiculoClienteId).OnDelete(DeleteBehavior.Restrict);m.Entity<ItemOrdemServico>().HasOne(x=>x.OrdemServico).WithMany(x=>x.Itens).HasForeignKey(x=>x.OrdemServicoId);m.Entity<OportunidadeCrm>().HasOne(x=>x.Cliente).WithMany().HasForeignKey(x=>x.ClienteId).OnDelete(DeleteBehavior.Restrict);m.Entity<InteracaoCrm>().HasOne(x=>x.Oportunidade).WithMany(x=>x.Interacoes).HasForeignKey(x=>x.OportunidadeCrmId);m.Entity<VendaPerdida>().HasOne(x=>x.Cliente).WithMany().HasForeignKey(x=>x.ClienteId).OnDelete(DeleteBehavior.Restrict);m.Entity<VendaPerdida>().HasOne(x=>x.Produto).WithMany().HasForeignKey(x=>x.ProdutoId).OnDelete(DeleteBehavior.Restrict);m.Entity<PermissaoPerfil>().HasIndex(x=>new{x.Perfil,x.Modulo}).IsUnique();m.Entity<VersaoBanco>().HasIndex(x=>x.Versao).IsUnique();
m.Entity<CotacaoCompra>().HasIndex(x=>x.Numero).IsUnique();
m.Entity<ItemCotacaoCompra>().HasOne(x=>x.CotacaoCompra).WithMany(x=>x.Itens).HasForeignKey(x=>x.CotacaoCompraId);
m.Entity<OfertaFornecedor>().HasOne(x=>x.Item).WithMany(x=>x.Ofertas).HasForeignKey(x=>x.ItemCotacaoCompraId);
m.Entity<ComissaoVenda>().HasOne(x=>x.Venda).WithMany().HasForeignKey(x=>x.VendaId).OnDelete(DeleteBehavior.Restrict);
}
}
