using System.Windows;using AutoPecasERP.Core.Entities;using AutoPecasERP.Core.Models;using AutoPecasERP.Data.Context;using AutoPecasERP.Services.Financeiro;using Microsoft.EntityFrameworkCore;
namespace AutoPecasERP.Desktop.Views;
public partial class CentroFinanceiroWindow:Window{readonly Usuario _u;readonly ErpDbContext _db=new();readonly FinanceiroService _svc;List<TituloFinanceiroView> _todos=new();public CentroFinanceiroWindow(Usuario u){InitializeComponent();_u=u;_svc=new(_db);Loaded+=async(_,__)=>{FiltroTipo.SelectedIndex=0;await Atualizar();};}
async Task Atualizar(){_todos=await _svc.TitulosAsync();var cr=_todos.Where(x=>x.Tipo=="RECEBER").Sum(x=>x.Saldo);var cp=_todos.Where(x=>x.Tipo=="PAGAR").Sum(x=>x.Saldo);ReceberTxt.Text=cr.ToString("C");PagarTxt.Text=cp.ToString("C");AtrasadoTxt.Text=_todos.Where(x=>x.Atrasado).Sum(x=>x.Saldo).ToString("C");var c=await _db.Caixas.FirstOrDefaultAsync(x=>x.Status=="ABERTO");CaixaTxt.Text=c?.SaldoCalculado.ToString("C")??"FECHADO";Aplicar();}
void Aplicar(){IEnumerable<TituloFinanceiroView> q=_todos;var tipo=((System.Windows.Controls.ComboBoxItem?)FiltroTipo.SelectedItem)?.Content?.ToString();if(tipo=="RECEBER"||tipo=="PAGAR")q=q.Where(x=>x.Tipo==tipo);if(tipo=="ATRASADOS")q=q.Where(x=>x.Atrasado);var b=BuscaBox.Text.Trim();if(b.Length>0)q=q.Where(x=>x.Pessoa.Contains(b,StringComparison.OrdinalIgnoreCase)||x.Descricao.Contains(b,StringComparison.OrdinalIgnoreCase));Grid.ItemsSource=q.ToList();}
async void Baixar_Click(object s,RoutedEventArgs e){if(Grid.SelectedItem is not TituloFinanceiroView t){MessageBox.Show("Selecione um título.");return;}var d=new ValorDialog($"Baixar conta a {t.Tipo.ToLower()}",t.Saldo){Owner=this};if(d.ShowDialog()!=true)return;try{if(t.Tipo=="RECEBER")await _svc.ReceberAsync(t.Id,d.Valor,"DINHEIRO",_u.Nome);else await _svc.BaixarContaPagarAsync(t.Id,d.Valor,"DINHEIRO",_u.Nome);await Atualizar();}catch(Exception ex){MessageBox.Show(ex.Message);}}
async void AbrirCaixa_Click(object s,RoutedEventArgs e){var d=new ValorDialog("Abertura de caixa",0){Owner=this};if(d.ShowDialog()==true){try{await _svc.AbrirCaixaAsync(d.Valor,_u.Nome);await Atualizar();}catch(Exception ex){MessageBox.Show(ex.Message);}}}
async void Suprimento_Click(object s,RoutedEventArgs e){var d=new ValorDialog("Suprimento"){Owner=this};if(d.ShowDialog()==true){try{await _svc.MovimentarAsync("SUPRIMENTO",d.Valor,d.Observacao,_u.Nome);await Atualizar();}catch(Exception ex){MessageBox.Show(ex.Message);}}}
async void Sangria_Click(object s,RoutedEventArgs e){var d=new ValorDialog("Sangria"){Owner=this};if(d.ShowDialog()==true){try{await _svc.MovimentarAsync("SANGRIA",d.Valor,d.Observacao,_u.Nome);await Atualizar();}catch(Exception ex){MessageBox.Show(ex.Message);}}}
async void FecharCaixa_Click(object s,RoutedEventArgs e){var d=new ValorDialog("Saldo contado"){Owner=this};if(d.ShowDialog()==true){try{var c=await _svc.FecharCaixaAsync(d.Valor,_u.Nome);MessageBox.Show($"Calculado: {c.SaldoCalculado:C}\nContado: {c.SaldoInformado:C}\nDiferença: {c.Diferenca:C}");await Atualizar();}catch(Exception ex){MessageBox.Show(ex.Message);}}}
void Filtro_Changed(object s,System.Windows.Controls.SelectionChangedEventArgs e){if(IsLoaded)Aplicar();}void Busca_Changed(object s,System.Windows.Controls.TextChangedEventArgs e){if(IsLoaded)Aplicar();}async void Atualizar_Click(object s,RoutedEventArgs e)=>await Atualizar();}