using System.Collections.ObjectModel;using System.Globalization;using System.Windows;using System.Windows.Input;using AutoPecasERP.Core.Entities;using AutoPecasERP.Core.Models;using AutoPecasERP.Data.Context;using AutoPecasERP.Services.Vendas;using Microsoft.EntityFrameworkCore;
namespace AutoPecasERP.Desktop.Views;
public partial class PdvProfissionalWindow:Window{readonly ErpDbContext _db=new();readonly Usuario _u;readonly ObservableCollection<PdvCarrinhoItem> _itens=new();decimal _desconto;
public PdvProfissionalWindow(Usuario u){InitializeComponent();_u=u;VendedorBox.Text=u.Nome;CarrinhoGrid.ItemsSource=_itens;Loaded+=async(_,__)=>{ClienteBox.ItemsSource=await _db.Clientes.Where(x=>x.Ativo).OrderBy(x=>x.Nome).ToListAsync();PagamentoBox.SelectedIndex=0;BuscaBox.Focus();};}
decimal Parse(string s)=>decimal.TryParse(s,NumberStyles.Number,CultureInfo.GetCultureInfo("pt-BR"),out var v)?v:0;
async Task Adicionar(){var q=BuscaBox.Text.Trim();if(string.IsNullOrWhiteSpace(q))return;var p=await _db.Produtos.FirstOrDefaultAsync(x=>x.Ativo&&(x.CodigoInterno==q||x.CodigoBarras==q));if(p==null)p=await _db.Produtos.FirstOrDefaultAsync(x=>x.Ativo&&x.Descricao.Contains(q));if(p==null){MessageBox.Show("Produto não encontrado.");return;}var qtd=Parse(QtdBox.Text);if(qtd<=0){MessageBox.Show("Quantidade inválida.");return;}var existente=_itens.FirstOrDefault(x=>x.ProdutoId==p.Id);if(existente!=null){existente.Quantidade+=qtd;CarrinhoGrid.Items.Refresh();}else _itens.Add(new PdvCarrinhoItem{ProdutoId=p.Id,Codigo=p.CodigoInterno,Descricao=p.Descricao,Quantidade=qtd,Unitario=p.PrecoVenda});BuscaBox.Clear();QtdBox.Text="1";Atualizar();BuscaBox.Focus();}
void Atualizar(){var sub=_itens.Sum(x=>x.Total);if(_desconto<0)_desconto=0;if(_desconto>sub)_desconto=sub;SubtotalTxt.Text=sub.ToString("C");TotalTxt.Text=(sub-_desconto).ToString("C");}
async void Adicionar_Click(object s,RoutedEventArgs e)=>await Adicionar();async void Busca_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.Enter)await Adicionar();}
void Remover_Click(object s,RoutedEventArgs e){if(CarrinhoGrid.SelectedItem is PdvCarrinhoItem i)_itens.Remove(i);Atualizar();}
void Desconto_LostFocus(object s,RoutedEventArgs e){_desconto=Parse(DescontoBox.Text);Atualizar();}
async void Finalizar_Click(object s,RoutedEventArgs e){if(!_itens.Any()){MessageBox.Show("Carrinho vazio.");return;}if(ClienteBox.SelectedItem is not Cliente c){MessageBox.Show("Selecione o cliente.");return;}var sub=_itens.Sum(x=>x.Total);_desconto=Parse(DescontoBox.Text);if(_desconto<0||_desconto>sub){MessageBox.Show("Desconto inválido.");return;}if(_desconto>sub*.10m&&_u.Perfil!=PerfilUsuario.Administrador&&_u.Perfil!=PerfilUsuario.Gerente){MessageBox.Show("Desconto acima de 10% exige autorização de gerente/administrador.");return;}var forma=((System.Windows.Controls.ComboBoxItem)PagamentoBox.SelectedItem).Content?.ToString()??"DINHEIRO";try{var itens=_itens.Select(x=>new VendaService.ItemInput(x.ProdutoId,x.Quantidade,x.Unitario,x.Desconto)).ToList();var venda=await new VendaService(_db).FinalizarAsync(c.Id,itens,_desconto,forma,VendedorBox.Text,_u.Nome);var f=new FiscalVendaWindow(venda.Id){Owner=this};f.ShowDialog();_itens.Clear();_desconto=0;DescontoBox.Text="0";Atualizar();}catch(Exception ex){MessageBox.Show(ex.Message);}}
void Window_KeyDown(object s,KeyEventArgs e){if(e.Key==Key.F2)BuscaBox.Focus();else if(e.Key==Key.F4)ClienteBox.Focus();else if(e.Key==Key.Delete)Remover_Click(s,new RoutedEventArgs());else if(e.Key==Key.F8)Finalizar_Click(s,new RoutedEventArgs());}}