using System.Collections.ObjectModel; using System.Windows; using System.Windows.Input; using AutoPecasERP.Core.Entities; using AutoPecasERP.Data.Context; using AutoPecasERP.Services.Vendas; using Microsoft.EntityFrameworkCore;
namespace AutoPecasERP.Desktop.Views;
public partial class PdvWindow:Window {
 readonly Usuario _usuario; readonly ErpDbContext _db=new(); public ObservableCollection<LinhaPdv> Itens {get;}=new();
 public PdvWindow(Usuario usuario){InitializeComponent();_usuario=usuario;GridItens.ItemsSource=Itens;PagamentoBox.ItemsSource=new[]{"DINHEIRO","PIX","CARTAO","BOLETO","CREDIARIO"};PagamentoBox.SelectedIndex=0;Loaded+=async(_,__)=>ClienteBox.ItemsSource=await _db.Clientes.Where(x=>x.Ativo).OrderBy(x=>x.Nome).ToListAsync();KeyDown+=(_,e)=>{if(e.Key==Key.F6)Finalizar_Click(this,new RoutedEventArgs());};}
 async void Busca_KeyDown(object s,KeyEventArgs e){if(e.Key!=Key.Enter)return;var q=Busca.Text.Trim();var p=await _db.Produtos.FirstOrDefaultAsync(x=>x.CodigoInterno==q||x.CodigoBarras==q); if(p==null) p=await _db.Produtos.FirstOrDefaultAsync(x=>x.Descricao.Contains(q));if(p==null){MessageBox.Show("Produto não encontrado.");return;}var l=Itens.FirstOrDefault(x=>x.ProdutoId==p.Id);if(l==null)Itens.Add(new LinhaPdv{ProdutoId=p.Id,Codigo=p.CodigoInterno,Descricao=p.Descricao,Quantidade=1,ValorUnitario=p.PrecoVenda});else l.Quantidade++;GridItens.Items.Refresh();Busca.Clear();AtualizaTotal();}
 void AtualizaTotal(){var total=Itens.Sum(x=>x.Total);if(decimal.TryParse(DescontoBox.Text,out var d))total-=d;TotalText.Text=$"TOTAL {total:C}";}
 async void Finalizar_Click(object s,RoutedEventArgs e){try{decimal.TryParse(DescontoBox.Text,out var d);var cliente=ClienteBox.SelectedItem as Cliente;var venda=await new VendaService(_db).FinalizarAsync(cliente?.Id,_usuario.Id,_usuario.Nome,PagamentoBox.SelectedItem?.ToString()??"DINHEIRO",d,Itens.Select(x=>new ItemVendaInput(x.ProdutoId,x.Quantidade,x.ValorUnitario,0)));MessageBox.Show($"Venda {venda.Numero} concluída.\n\nPróximo passo fiscal: NF-e / NFC-e / Somente venda.","Venda concluída");new FiscalVendaWindow(venda.Id){Owner=this}.ShowDialog();Itens.Clear();AtualizaTotal();}catch(Exception ex){MessageBox.Show(ex.Message,"Não foi possível finalizar",MessageBoxButton.OK,MessageBoxImage.Warning);}}
}
public class LinhaPdv{public int ProdutoId{get;set;}public string Codigo{get;set;}="" ;public string Descricao{get;set;}="";public decimal Quantidade{get;set;}public decimal ValorUnitario{get;set;}public decimal Total=>Quantidade*ValorUnitario;}