using AutoPecasERP.Core.Entities;using AutoPecasERP.Data.Context;using Microsoft.EntityFrameworkCore;
namespace AutoPecasERP.Services.Financeiro;
public class FinanceiroService{readonly ErpDbContext _db;public FinanceiroService(ErpDbContext db)=>_db=db;
public Task<Caixa?> CaixaAbertoAsync()=>_db.Caixas.Include(x=>x.Movimentos).FirstOrDefaultAsync(x=>x.Status=="ABERTO");
public async Task<Caixa> AbrirCaixaAsync(decimal inicial,string usuario){if(await CaixaAbertoAsync()!=null)throw new InvalidOperationException("Já existe caixa aberto.");var c=new Caixa{SaldoInicial=inicial,UsuarioAbertura=usuario};_db.Caixas.Add(c);await _db.SaveChangesAsync();return c;}
public async Task MovimentarAsync(string tipo,decimal valor,string historico,string usuario,string forma="DINHEIRO",string origem="MANUAL",int? origemId=null){if(valor<=0)throw new InvalidOperationException("Valor deve ser maior que zero.");var c=await CaixaAbertoAsync()??throw new InvalidOperationException("Abra o caixa primeiro.");_db.MovimentosCaixa.Add(new MovimentoCaixa{CaixaId=c.Id,Tipo=tipo,Valor=valor,Historico=historico,Usuario=usuario,FormaPagamento=forma,Origem=origem,OrigemId=origemId});await _db.SaveChangesAsync();}
public async Task BaixarReceberAsync(int tituloId,decimal valor,string forma,string usuario){var t=await _db.ContasReceber.FindAsync(tituloId)??throw new InvalidOperationException("Título não encontrado.");if(t.Status=="PAGO")throw new InvalidOperationException("Título já pago.");var jaPago=await _db.BaixasFinanceiras.Where(x=>x.TipoTitulo=="RECEBER"&&x.TituloId==t.Id).SumAsync(x=>(decimal?)x.Valor)??0;var saldo=t.Valor-jaPago;if(valor<=0||valor>saldo)throw new InvalidOperationException($"Valor de baixa inválido. Saldo: {saldo:C}.");var c=await CaixaAbertoAsync()??throw new InvalidOperationException("Abra o caixa.");_db.BaixasFinanceiras.Add(new BaixaFinanceira{TituloId=t.Id,TipoTitulo="RECEBER",Valor=valor,FormaPagamento=forma,CaixaId=c.Id,Usuario=usuario});_db.MovimentosCaixa.Add(new MovimentoCaixa{CaixaId=c.Id,Tipo="ENTRADA",Origem="CONTA_RECEBER",OrigemId=t.Id,FormaPagamento=forma,Valor=valor,Historico=t.Descricao,Usuario=usuario});t.Status=jaPago+valor>=t.Valor?"PAGO":"PARCIAL";await _db.SaveChangesAsync();}
public Task ReceberAsync(int id,decimal valor,string forma,string usuario)=>BaixarReceberAsync(id,valor,forma,usuario);public Task<Caixa> FecharCaixaAsync(decimal saldo,string usuario)=>FecharAsync(saldo,usuario);public async Task<Caixa> FecharAsync(decimal saldoInformado,string usuario){var c=await CaixaAbertoAsync()??throw new InvalidOperationException("Nenhum caixa aberto.");var ent=c.Movimentos.Where(x=>x.Tipo is "ENTRADA" or "SUPRIMENTO").Sum(x=>x.Valor);var sai=c.Movimentos.Where(x=>x.Tipo is "SAIDA" or "SANGRIA").Sum(x=>x.Valor);c.SaldoCalculado=c.SaldoInicial+ent-sai;c.SaldoFinalInformado=saldoInformado;c.Fechamento=DateTime.Now;c.UsuarioFechamento=usuario;c.Status="FECHADO";await _db.SaveChangesAsync();return c;}public async Task BaixarContaPagarAsync(int id,decimal valor,string forma,string usuario){var t=await _db.ContasPagar.SingleAsync(x=>x.Id==id);if(valor<=0)throw new InvalidOperationException("Valor inválido.");var pagos=await _db.BaixasFinanceiras.Where(x=>x.TipoTitulo=="PAGAR"&&x.TituloId==id).SumAsync(x=>(decimal?)x.Valor)??0;var restante=t.Valor-pagos;if(valor>restante)throw new InvalidOperationException($"Valor acima do saldo ({restante:C}).");var caixa=await _db.Caixas.FirstOrDefaultAsync(x=>x.Status=="ABERTO");await using var tx=await _db.Database.BeginTransactionAsync();_db.BaixasFinanceiras.Add(new BaixaFinanceira{TipoTitulo="PAGAR",TituloId=id,Valor=valor,Forma=forma,Data=DateTime.Now,Usuario=usuario});if(caixa!=null){caixa.SaldoCalculado-=valor;_db.MovimentosCaixa.Add(new MovimentoCaixa{CaixaId=caixa.Id,Tipo="SAIDA",Valor=valor,Forma=forma,Descricao=$"Pagamento CP #{id}",Data=DateTime.Now,Usuario=usuario});}if(pagos+valor>=t.Valor)t.Status="PAGO";await _db.SaveChangesAsync();await tx.CommitAsync();}
public async Task<List<AutoPecasERP.Core.Models.TituloFinanceiroView>> TitulosAsync(){var r=new List<AutoPecasERP.Core.Models.TituloFinanceiroView>();var cr=await _db.ContasReceber.Include(x=>x.Cliente).ToListAsync();foreach(var x in cr){var pago=await _db.BaixasFinanceiras.Where(b=>b.TipoTitulo=="RECEBER"&&b.TituloId==x.Id).SumAsync(b=>(decimal?)b.Valor)??0;r.Add(new(){Id=x.Id,Tipo="RECEBER",Pessoa=x.Cliente?.Nome??"",Descricao=x.Descricao,Vencimento=x.Vencimento,Valor=x.Valor,Pago=pago,Status=x.Status});}var cp=await _db.ContasPagar.Include(x=>x.Fornecedor).ToListAsync();foreach(var x in cp){var pago=await _db.BaixasFinanceiras.Where(b=>b.TipoTitulo=="PAGAR"&&b.TituloId==x.Id).SumAsync(b=>(decimal?)b.Valor)??0;r.Add(new(){Id=x.Id,Tipo="PAGAR",Pessoa=x.Fornecedor?.NomeFantasia??x.Fornecedor?.RazaoSocial??"",Descricao=x.Descricao,Vencimento=x.Vencimento,Valor=x.Valor,Pago=pago,Status=x.Status});}return r.OrderBy(x=>x.Vencimento).ToList();}
}